services:

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    restart: always
    command: server standalone
    depends_on:
      - timescaledb
    ports:
      - "8080:8080"
    volumes:
      - ./kestra:/app/storage
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://timescaledb:5432/analytics
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra

        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          server:
            security:
              basic-auth:
                enabled: true
                username: admin@local.com
                password: admin123

  kestra-worker:
    build:
      context: .
      dockerfile: ./kestra-worker/Dockerfile
    image: weather-kestra-worker
    container_name: kestra-worker
    command: server worker
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://timescaledb:5432/analytics
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra

        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          server:
            url: http://kestra:8080

            
    volumes:
      - ../ingestion:/app/ingestion
      - ../bruin:/app/bruin
    depends_on:
      - kestra

  metabase-db:
    image: postgres:15
    container_name: metabase-db
    restart: always
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
      POSTGRES_DB: metabase
    volumes:
      - metabase_db-data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    depends_on:
      - metabase-db
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_SIGNUP_ENABLED: false
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: kestra
      MB_DB_PASS: kestra
      MB_DB_HOST: metabase-db

volumes:
  timescale_data:
  metabase_data:
  metabase_db-data: